### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=WebStorm

###

POST http://localhost:3000/boards
Content-Type: application/json

{
  "title": "안녕하세요",
  "description": "그렇습니다."
}

###

POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "username": "dolosolo",
  "password": "free66"
}

###

GET http://localhost:3000/auth/dolosolo
Content-Type: application/json

